service: whois

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  stage: ${opt:stage, 'dev'}

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    SLACK_DATA_URL: ${file(./config.js):${self:custom.stage}.SLACK_DATA_URL}

package:
  exclude:
    - .env

functions:
  api:
    handler: src/server.handler
    events:
      - http: ANY /

      - http: 'ANY {proxy+}'
