service: whois

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

package:
  exclude:
    - .env

functions:
  api:
    handler: src/server.handler
    events:
      - http: ANY /

      - http: 'ANY {proxy+}'
