on:
  push:
    branches:
      - master
name: Serverless deploy master branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing Dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Decrypting Environment Secrets
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: decrypt:env
      - name: Deploying
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: deploy:prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BOT_ENCRYPTION_KEY: ${{ secrets.BOT_ENCRYPTION_KEY }}
